apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-unff
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-unff
    app.kubernetes.io/part-of: test-app-vzgc
  name: devfile-sample-python-basic-unff
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-unff
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-unff
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-umwv-tenant/test-app-vzgc/devfile-sample-python-basic-unff@sha256:25673ee0c00fd3a81af3498863be5b9438084fce39d2e7cbde73398934493c86
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
