apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-no-dockerfile-wrul
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-umwv-tenant/test-app-vzgc/nodejs-no-dockerfile-wrul@sha256:3fcce420b3a098e9469be0e23e2da733f94fc83e4e61e39c51e6b304a951b06b
        name: my-nodejs
        resources: {}
status: {}
