apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-wrul
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-wrul
    app.kubernetes.io/part-of: test-app-vzgc
  name: nodejs-no-dockerfile-wrul
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-wrul
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-wrul
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-umwv-tenant/test-app-vzgc/nodejs-no-dockerfile-wrul@sha256:3fcce420b3a098e9469be0e23e2da733f94fc83e4e61e39c51e6b304a951b06b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
